In [1]:
import math
from Utils.hdfs import init
from Utils.dataFrameSize import dfSizeEstimator
from pyspark.sql import SparkSession
from pyspark.sql import types as T
from pyspark.sql import functions as F

In [2]:
builder = (
    SparkSession.builder
    .appName("ingest_data_from_rawfile")
    .master("yarn")
    # .config("spark.yarn.am.memory", "512m")
    # .config("spark.driver.memory", "512m")
    # .config("spark.executor.memory", "512m")
    # .config("spark.executor.cores", "1")
    # .config("spark.executor.instances", "1")
    .config("spark.dynamicAllocation.enabled", "true")
    .config("spark.sql.shuffle.partitions", "8")
    .config("spark.jars.packages", "io.delta:delta-spark_2.12:3.2.0")
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
    .config("spark.sql.catalogImplementation", "hive")
    .config("spark.hadoop.hive.metastore.uris", "thrift://hive-metastore:9083")
    .enableHiveSupport()
)
spark = builder.getOrCreate()

In [3]:
init(spark)

In [4]:
%%hdfs
ls /user/jovyan/rawdata

PERMISSIONS  REPL OWNER      GROUP                 SIZE MODIFIED             NAME
------------------------------------------------------------------------------------------------------------------------
-rwxrwxr-x   1    jovyan     supergroup       622183749 2026-07-05 12:00:39.029000 flight_data.csv

In [5]:
schema = T.StructType([
    T.StructField('departure_time', T.StringType(), True),
    T.StructField('arrival_time', T.StringType(), True),
    T.StructField('flight_id', T.StringType(), True),
    T.StructField('aircraft_id', T.StringType(), True),
    T.StructField('itinerary_no', T.StringType(), True),
    T.StructField('ticket_no', T.StringType(), True),
    T.StructField('flight_cost', T.StringType(), True),
    T.StructField('origin_airport', T.StringType(), True),
    T.StructField('destination_airport', T.StringType(), True),
    T.StructField('frequent_flier', T.StringType(), True),
    T.StructField('travel_date', T.StringType(), True),
    T.StructField('airplane_model', T.StringType(), True),
    T.StructField('frequent_flier_no', T.StringType(), True),
    T.StructField('passenger_name', T.StringType(), True),
    T.StructField('passenger_country', T.StringType(), True),
    T.StructField('tail_no', T.StringType(), True),
    T.StructField('distance', T.StringType(), True),
    T.StructField('turbulance', T.StringType(), True),
    T.StructField('temp_at_dept', T.StringType(), True),
    T.StructField('fuel_consumed_litre', T.StringType(), True),
    T.StructField('taxi_duration_mins', T.StringType(), True),
    T.StructField('avg_flight_speed_kmps', T.StringType(), True),
    T.StructField('engine_performance', T.StringType(), True),
    T.StructField('passenger_dob', T.StringType(), True),
    T.StructField('passenger_flight_class', T.StringType(), True)
])

In [6]:
df = spark.read.format('csv').schema(schema).load('hdfs:///user/jovyan/rawdata/flight_data.csv')

In [7]:
df.limit(10).show()

+--------------+------------+---------+-----------+------------+---------------+-----------+--------------+--------------------+--------------+-----------+--------------------+-----------------+--------------+-----------------+-------+--------+----------+------------+-------------------+------------------+---------------------+------------------+-------------+----------------------+
|departure_time|arrival_time|flight_id|aircraft_id|itinerary_no|      ticket_no|flight_cost|origin_airport| destination_airport|frequent_flier|travel_date|      airplane_model|frequent_flier_no|passenger_name|passenger_country|tail_no|distance|turbulance|temp_at_dept|fuel_consumed_litre|taxi_duration_mins|avg_flight_speed_kmps|engine_performance|passenger_dob|passenger_flight_class|
+--------------+------------+---------+-----------+------------+---------------+-----------+--------------+--------------------+--------------+-----------+--------------------+-----------------+--------------+-----------------+-------+--------+----------+------------+-------------------+------------------+---------------------+------------------+-------------+----------------------+
|      14:55:24|    15:36:24| ZFX62337|      AI921|    65699650|WA-74444-XH-663|     873.13|   Thomasville|        Broken Arrow|         False| 2024-10-31|  Cessna Citation VI|             NULL|        Jeffry| Marshall Islands| K916KT|    5125|         0|       -11.4|            59852.8|              63.0|               1059.2|             38490|   2009-10-17|               economy|
|      13:46:24|    14:29:24| HHA25662|      AI600|    61802452|RB-94145-CY-313|     696.97|        Oviedo|           Englewood|          True| 2025-01-09|Gulfstream Aerosp...|         946517EI|     Katharina|      Afghanistan| U968EO|    1043|         4|         8.3|            14717.8|              91.0|                812.8|             11960|   2006-12-30|               economy|
|      02:08:24|    04:28:24| OHV91711|      AI364|    68709962|HF-40394-DP-864|    4822.69|   Lindenhurst|           Massillon|         False| 2025-01-19|             ICON A5|             NULL|         Clair|       Montserrat| D134FD|    2034|         0|         6.5|            18145.2|              30.0|                924.7|             16549|   2009-08-14|               economy|
|      17:12:24|    19:57:24| OOW61906|      AI729|    69569900|NT-63599-MM-074|     783.19|    Buena Park|          Round Rock|          True| 2024-06-06|      Boeing 767-200|         748932HI|      Marketta|       Bangladesh| L238GB|    4181|         0|         1.4|            69484.8|              35.0|               1362.6|             30980|   2007-01-25|               economy|
|      13:24:24|    14:58:24| QUN94363|      AI261|    66712064|PH-79868-LM-843|    1376.19|    Ponca City|Rancho Santa Marg...|          True| 2025-02-17|Cessna 177 Cardin...|         767393RE|         Veola|     Diego Garcia| A073BE|    4057|         1|       -14.0|            58651.1|              76.0|               1178.2|             25889|   2000-01-13|               economy|
|      04:33:24|    06:06:24| TBK38067|      AI262|    62797208|IV-75212-HI-274|    5826.54|        Eugene|             Bothell|         False| 2024-06-01|Pilatus Britten-N...|             NULL|         Colin|            Cocos| N841OZ|    5911|         0|        -5.6|            68370.9|             118.0|               1141.1|             40455|   1998-04-18|               economy|
|      08:25:24|    11:20:24| JBL75134|      AI861|    62432137|DZ-04653-OU-735|    3296.33| Redondo Beach|            Avondale|          True| 2024-07-16|  Shorts SC-7 Skyvan|         464084GC|        Kamala|          Bahamas| F176GQ|    1050|         8|       -11.9|            17742.8|              25.0|                805.8|             13569|   2007-06-21|               economy|
|      20:33:24|    23:26:24| HXZ38980|      AI648|    60685564|MK-69347-IN-525|     451.28|      Stafford|           Lakeville|          True| 2024-07-07|Hawker Siddeley H...|         769912HN|          Myrl|          Nigeria| D677IB|    2046|         1|       -14.3|            19807.1|              22.0|                947.9|             19748|   2007-11-26|               economy|
|      02:26:24|    03:01:24| CVD26712|      AI830|    69196488|NE-63712-TR-773|    3439.07|      Brockton|            Calexico|         False| 2024-11-28|           Avro RJ70|             NULL|       Stefany|             Guam| S455VO|    3055|         0|       -14.6|            41244.3|              30.0|                977.4|             27756|   2005-11-02|               economy|
|      10:56:24|    12:31:24| GTT06814|      AI538|    68810759|HU-37986-VX-434|     770.65|        Dinuba|       Mission Viejo|          True| 2025-02-18|     Pipistrel Sinus|         963521PS|          Roxy|          Mayotte| T297KV|     670|         7|        -8.2|             7443.3|             107.0|                585.7|              7958|   2008-03-05|               economy|
+--------------+------------+---------+-----------+------------+---------------+-----------+--------------+--------------------+--------------+-----------+--------------------+-----------------+--------------+-----------------+-------+--------+----------+------------+-------------------+------------------+---------------------+------------------+-------------+----------------------+

In [8]:
%%sql
create database warehouse;

Empty DataFrame
Columns: []
Index: []

In [12]:
%%hdfs
ls /user

PERMISSIONS  REPL OWNER      GROUP                 SIZE MODIFIED             NAME
------------------------------------------------------------------------------------------------------------------------
drwxrwxr-x   0    jovyan     supergroup               0 2026-07-05 12:04:08.889000 jovyan

In [9]:
%%sql
use warehouse;

Empty DataFrame
Columns: []
Index: []

In [10]:
df.repartition(max(
    3, #number of executors
    math.ceil(dfSizeEstimator(df, True)) / 200)).write.mode('overwrite').format('delta')\
    .option("path", "hdfs:///user/jovyan/lakehouse/bronze/flight")\
    .saveAsTable('warehouse.flight_raw')

In [11]:
df.rdd.getNumPartitions()

5

In [12]:
%%sql
select *
from delta.`hdfs:///user/jovyan/lakehouse/bronze/flight` limit 3;

,departure_time,arrival_time,flight_id,aircraft_id,itinerary_no,ticket_no,flight_cost,origin_airport,destination_airport,frequent_flier,...,tail_no,distance,turbulance,temp_at_dept,fuel_consumed_litre,taxi_duration_mins,avg_flight_speed_kmps,engine_performance,passenger_dob,passenger_flight_class
0,22:08:41,23:57:41,CCK50278,AI947,61143910,SS-34573-UW-271,3940.67,Cape Coral,Paducah,True,...,S873RN,1724,0,-7.5,24177.5,25.0,834.3,12773,1999-11-08,economy
1,18:29:30,19:17:30,BRT38419,AI438,68917462,NT-33366-BW-995,698.1,Carrboro,Hilliard,True,...,H544XD,5842,0,-7.3,59102.8,120.0,1127.3,46453,2001-01-27,economy
2,13:32:41,15:14:41,KEU89486,AI045,62198786,BR-03300-EE-686,784.61,North Richland Hills,Central Falls,False,...,Z674GW,2008,1,-9.7,19477.8,84.0,945.9,18050,2003-03-13,economy

In [13]:
%%sql
select * from (
select row_number() over (order by add) as rn, a.* 
from json.`hdfs:///user/jovyan/lakehouse/bronze/flight/_delta_log/00000000000000000000.json` a)
where rn = 4;

Stored Spark DataFrame in 'output'

In [14]:
output = output.toPandas().to_numpy().tolist()[0][1]

In [15]:
import ast

In [16]:
output = ast.literal_eval(output.asDict()['stats'])

In [17]:
output

{'numRecords': 1000001,
 'minValues': {'departure_time': '00:00:00',
  'arrival_time': '00:00:00',
  'flight_id': 'AAA00237',
  'aircraft_id': 'AI000',
  'itinerary_no': '60000005',
  'ticket_no': 'AA-00019-TA-797',
  'flight_cost': '1000.0',
  'origin_airport': 'Aberdeen',
  'destination_airport': 'Aberdeen',
  'frequent_flier': 'False',
  'travel_date': '2024-05-13',
  'airplane_model': '"Airbus A300-600ST ""Beluga"""',
  'frequent_flier_no': '000001YV',
  'passenger_name': 'Aaron',
  'passenger_country': 'Afghanistan',
  'tail_no': 'A000AJ',
  'distance': '1000',
  'turbulance': '0',
  'temp_at_dept': '-0.0',
  'fuel_consumed_litre': '12000.0',
  'taxi_duration_mins': '100.0',
  'avg_flight_speed_kmps': '1000.0',
  'engine_performance': '10000',
  'passenger_dob': '1998-01-01',
  'passenger_flight_class': 'economy'},
 'maxValues': {'departure_time': '23:59:59',
  'arrival_time': '23:59:59',
  'flight_id': 'ZZZ98392',
  'aircraft_id': 'AI999',
  'itinerary_no': '69999996',
  'ticket_no': 'ZZ-99988-XB-301',
  'flight_cost': '999.99',
  'origin_airport': 'Zion',
  'destination_airport': 'Zion',
  'frequent_flier': 'True',
  'travel_date': '2025-03-08',
  'airplane_model': 'Yakovlev Yak-42',
  'frequent_flier_no': '999999YX',
  'passenger_name': 'Zulma',
  'passenger_country': 'Åland Islands',
  'tail_no': 'Z999ZI',
  'distance': '999',
  'turbulance': '8',
  'temp_at_dept': '9.9',
  'fuel_consumed_litre': '7996.1',
  'taxi_duration_mins': '99.0',
  'avg_flight_speed_kmps': '999.9',
  'engine_performance': '8000',
  'passenger_dob': '2010-12-31',
  'passenger_flight_class': 'economy'},
 'nullCount': {'departure_time': 0,
  'arrival_time': 0,
  'flight_id': 0,
  'aircraft_id': 0,
  'itinerary_no': 0,
  'ticket_no': 0,
  'flight_cost': 0,
  'origin_airport': 0,
  'destination_airport': 0,
  'frequent_flier': 0,
  'travel_date': 0,
  'airplane_model': 0,
  'frequent_flier_no': 501100,
  'passenger_name': 0,
  'passenger_country': 0,
  'tail_no': 0,
  'distance': 0,
  'turbulance': 0,
  'temp_at_dept': 0,
  'fuel_consumed_litre': 0,
  'taxi_duration_mins': 0,
  'avg_flight_speed_kmps': 0,
  'engine_performance': 0,
  'passenger_dob': 0,
  'passenger_flight_class': 0}}